// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815191604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the basics of C# programming language.",
                            DurationInHours = 20,
                            Name = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build web applications using ASP.NET Core.",
                            DurationInHours = 30,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Master database access using EF Core.",
                            DurationInHours = 15,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Introduction to relational databases and SQL.",
                            DurationInHours = 18,
                            Name = "SQL Server Basics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Build modern front-end applications using React.",
                            DurationInHours = 25,
                            Name = "React JS"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Student_Age", "[Age]>=16");

                            t.HasCheckConstraint("CK_Student_Email", "[Email] like '%_@__%__%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Email = "aya.sonbaty@example.com",
                            FullName = "Aya Tamer",
                            Percentage = 92.50m
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            Percentage = 85.75m
                        },
                        new
                        {
                            Id = 3,
                            Age = 20,
                            Email = "sara.ahmed@example.com",
                            FullName = "Sara Ahmed",
                            Percentage = 78.30m
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Email = "mohamed.nabil@example.com",
                            FullName = "Mohamed Nabil",
                            Percentage = 88.00m
                        },
                        new
                        {
                            Id = 5,
                            Age = 19,
                            Email = "nour.hassan@example.com",
                            FullName = "Nour Hassan",
                            Percentage = 95.10m
                        },
                        new
                        {
                            Id = 6,
                            Age = 24,
                            Email = "youssef.adel@example.com",
                            FullName = "Youssef Adel",
                            Percentage = 70.45m
                        },
                        new
                        {
                            Id = 7,
                            Age = 21,
                            Email = "mariam.fathy@example.com",
                            FullName = "Mariam Fathy",
                            Percentage = 91.20m
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            Email = "karim.tarek@example.com",
                            FullName = "Karim Tarek",
                            Percentage = 82.60m
                        },
                        new
                        {
                            Id = 9,
                            Age = 20,
                            Email = "salma.ibrahim@example.com",
                            FullName = "Salma Ibrahim",
                            Percentage = 89.90m
                        },
                        new
                        {
                            Id = 10,
                            Age = 25,
                            Email = "ahmed.ragab@example.com",
                            FullName = "Ahmed Ragab",
                            Percentage = 76.85m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
